server:
  port: 8080

app:
  api-prefix: /api/v1
  services:
    profile: "http://localhost:8082/profile-manager"

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: task_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/task-manager/**
          filters:
            - StripPrefix=2

        - id: profile_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/profile-manager/**
          filters:
            - StripPrefix=2

        - id: websocket-route
          uri: ws://localhost:8084
          predicates:
            - Path=/ws-service/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true